services:
    Enhavo\Bundle\TemplateBundle\Menu\TemplateMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\TemplateBundle\Form\Type\TemplateType:
        arguments:
            - '%enhavo_template.template.model.class%'
        tags:
            - { name: form.type, alias: enhavo_template_template }

    Enhavo\Bundle\TemplateBundle\Block\ResourceBlockType:
        tags:
            - { name: enhavo_block.block }

    Enhavo\Bundle\TemplateBundle\Template\TemplateManager:
        public: true
        arguments:
            - '%enhavo_template.template%'
            - '@doctrine.orm.entity_manager'
            - '@translator'
        calls:
            - [setContainer, ['@service_container']]

    Enhavo\Bundle\TemplateBundle\Controller\TemplateController:
        arguments:
            - '@Enhavo\Bundle\TemplateBundle\Template\TemplateManager'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
            - [setTemplateResolver, ['@Enhavo\Bundle\AppBundle\Template\TemplateResolverInterface']]
        tags:
            - { name: controller.service_arguments }
            - { name: container.service_subscriber }

    Enhavo\Bundle\TemplateBundle\EventListener\TemplateDoctrineSubscriber:
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }

    Enhavo\Bundle\TemplateBundle\Router\TemplateStrategy:
        public: true
        arguments:
            - '@enhavo_template.template.repository'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: enhavo_route.strategy, alias: 'template' }

    Enhavo\Bundle\TemplateBundle\Init\InitTemplate:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Enhavo\Bundle\TemplateBundle\Template\TemplateManager'
            - '@enhavo_template.template.factory'
            - '@enhavo_template.template.repository'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: enhavo.init, alias: 'template' }
