
enhavo_template_admin_template_index:
    path: /template/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_template_admin_api_template_index
        _endpoint:
            type: admin

enhavo_template_admin_template_create:
    path: /template/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_template_admin_api_template_create
        _endpoint:
            type: admin

enhavo_template_admin_template_update:
    path: '/template/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_template_admin_api_template_update
        _endpoint:
            type: admin